kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: models-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3
  volumeMode: Filesystem
